version: '3.5'


volumes:
  data:
    driver: local

networks:
  game-net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1    

services:

  database:
    build: 
      context: ./database
      dockerfile: Dockerfile
    container_name: POSTGRES_DB
    restart: always
    networks:
      game-net:
        ipv4_address: 10.5.0.4   
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: game_state
      POSTGRES_USER: starrealms_app
      POSTGRES_PASSWORD: pwd
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - data:/var/lib/postgresql/data/

  adminer:
    image: docker.io/adminer
    container_name: adminer
    restart: always
    networks:
      game-net:
        ipv4_address: 10.5.0.5   
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: POSTGRES_DB:5432  
