version: '3.5'

volumes:
  db:
    driver: local

networks:
  starralms_net:
    driver: bridge

services:

  starrealms:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - starrealms_net
    ports:
      - 4040:4040 

  database:
    image: postgres:alpine
    container_name: POSTGRES_DB
    restart: always
    networks: 
      - starralms_net
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: game_state
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd

  adminer:
    image: adminer
    container_name: adminer
    networks: 
      - starralms_net  
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: POSTGRES_DB:5432  