version: '3.5'

volumes:
  db:
    driver: local

services:

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui
    restart: always
    ports:
      - 4040:80 
    environment:
      PUBLIC_URL: http://localhost/

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: gameserver
    restart: always
    ports:
      - 5000:80 
    environment:
      PORT: 80
      DB_SERVER: POSTGRES_DB:5432  
      DB_USER: starrealms_app
      DB_PASSWORD: pwd

  database:
    build: 
      context: ./database
      dockerfile: Dockerfile
    container_name: POSTGRES_DB
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: game_state
      POSTGRES_USER: starrealms_app
      POSTGRES_PASSWORD: pwd
    volumes:
      - db:/var/lib/postgresql/data/ 

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: POSTGRES_DB:5432  

  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    depends_on:
        - ui
        - api
    ports:
      - 80:80    