---
- name: deploy starrealms game server and db
  hosts: all
  
  tasks:

  - name: create network
    community.docker.docker_network:
      name: starrealms-net

  - name: Git checkout
    ansible.builtin.git:
      repo: 'https://github.com/sajonaro/star-realms.git'
      dest: /tmp/checkout

  - docker_image:
      name: gameserver
      source: build
      build:
        path: /tmp/checkout
        pull: false

  - name: delete code
    file:
      path: /tmp/checkout
      state: absent

  - name: deploy gameserver
    community.docker.docker_container:
      name: gameserver
      image: gameserver
      ports:
        - "4040:3000"
      networks:
        - name: starrealms-net          
      env:
        DB_SERVER: POSTGRES_DB:5432 
      restart_policy: always
        