--- 
- name: deploy starrealms game server and db
  hosts: all

  tasks:

  - name: create network
    community.docker.docker_network:
      name: starrealms-net
  
  - name: Git checkout
    ansible.builtin.git:
      repo: 'https://github.com/sajonaro/star-realms.git'
      dest: /tmp/checkout
  
  - name: Build gameserver image
    docker_image:
      name: gameserver
      build:
        path: /tmp/checkout
        dockerfile: ./Dockerfile
      source: build
      state: present  

  - name: deploy gameserver container
    docker_container:
      name: gameserver
      image: gameserver:latest
      state: started
      recreate: yes
      networks:
        - name: starrealms-net   
      exposed_ports:
        - 3000  
      ports:
        - "4040:3000"
      env:
        DB_SERVER: POSTGRES_DB:5432     