---
- name: deploy starrealms game server and db
  hosts: all
  
  tasks:

  - name: create network
    community.docker.docker_network:
      name: starrealms-net

  - name: Git checkout
    ansible.builtin.git:
      repo: 'https://github.com/sajonaro/star-realms.git'
      dest: /tmp/checkout

  - docker_image:
      name: gameserver
      source: build
      build:
        path: /tmp/checkout/Dockerfile
        pull: false

  - name: delete code
    file:
      path: /tmp/checkout
      state: absent      