openapi: 3.0.3
info:
  title: Star realms game API
  description: |-
    defined using Open API and swagger-editor tool
  version: 0.0.1
externalDocs:
  description: find out more about swagger.io
  url: http://swagger.io
servers:
  - url: http://localhost:4040/api/v1
    description: dev server
paths:
  /game:
    get:
      summary: get a list of games
      tags:
        - game
      operationId: getAllGames
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/games'
    post:
      tags:
        - game
      summary: create new game
      operationId: createGame
      requestBody:
        description: Create a new game
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/game'
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/game'          
        '405':
          description: Invalid input
      security:
        - starrealms_auth:
            - write:games
            - read:games
  /connect/{player_name}:
    post:
      tags:
        - player
      summary: login into game server
      description: no need to sign in to use the game.
      operationId: createPlayer
      parameters:
        - name: player_name
          in: path
          description: player name connecting to server
          required: true
          schema:
            type: string
      requestBody:
        description: Created player object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/player'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/player'
  /{gameId}/game/{playerId}/join:
    put:
      tags:
        - player
      summary: login into game server
      description: no need to sign in to use the game.
      operationId: joinGame
      parameters:
        - name: playerId
          in: path
          description: player's ID connecting to server
          required: true
          schema:
            type: integer
            format: int32
        - name: gameId
          in: path
          description: game ID player is willing to join
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        description: Created player object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/player'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/player'
components:
  schemas:
    player:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: theUser
        movesFirst:
          type: boolean
          description: true if this player moves first
          format: boolean
          example: true
    game:
      required:
        - id
        - createdBy
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        createdBy:
          type: string
          example: doggie
        players:
          type: array
          items:
            $ref: '#/components/schemas/player'
        status:
          type: string
          description: game status
          enum:
            - created
            - started
            - ended
    games:
      type: array
      items:
        $ref: '#/components/schemas/game'
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Pet:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
  securitySchemes:
    starrealms_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:games: modify games in your account
            read:games: read your games
    api_key:
      type: apiKey
      name: api_key
      in: header