version: '3.5'

volumes:
  db:
    driver: local

networks:
  starrealms_net:
    driver: bridge

services:

  starrealms:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: gameserver
    restart: always
    networks:
      - starrealms_net
    ports:
      - 4040:3000 
    environment:
      DB_SERVER: POSTGRES_DB:5432  

  database:
    build: 
      context: ../../src/db
      dockerfile: Dockerfile
    container_name: POSTGRES_DB
    restart: always
    networks: 
      - starrealms_net
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: game_state
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - ../../src/db/postgres-data:/var/lib/postgresql/data  

  adminer:
    image: adminer
    container_name: adminer
    networks: 
      - starrealms_net  
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: POSTGRES_DB:5432  